### ISSUE TITLE
关于软件打包输出问题

### ISSUE THREAD

**Issue by Blackwithking** [XDawned/ModpackLocalizationTools#3]
用的还是atm9-0.2.29版本

使用完软件将mod翻译之后，打包输出的资源包目录关系不正确
软件输出的mod翻译是：XX.zip/assets/mod/<各个mod的命名空间>/lang/zh_cn.json
实测这样游戏无法识别到翻译多了一层mod文件夹目录
更正为XX.zip/assets/<各个mod的命名空间>/lang/zh_cn.json
游戏可以识别到翻译并正确覆盖了

希望作者下次能改改这个乌龙bug

**Comment by XDawned** [comment]
感谢你的反馈，这个问题将在下个版本修复
