### ISSUE TITLE
这个软件的离线库会落后FTBQLocalizationTools吗

### ISSUE THREAD

**Issue by BlackRiceXY** [XDawned/ModpackLocalizationTools#4]

**Comment by XDawned** [comment]
- 在部分文本处理上可能会，两者共用的一套文本处理代码
  前者专注于文本处理，后者除此之外还需要考虑交互以及其它功能点
  所以前者更新周期会更长一些，除非是**致命性**的问题，否则不会为了文本处理方面的小优化单独发版
  因此在文本处理上可能会略晚于后者一到两个版本，但会在后续更新中会随着其它功能陆续对齐

**Comment by XDawned** [comment]
已在#v1.1.0版本同步
