### ISSUE TITLE
请重试，错误码：502 QIODevice::read (QFile, ":\qss\dark\gallery_interface.qss"): device not open

### ISSUE THREAD

**Issue by BlackRiceXY** [XDawned/ModpackLocalizationTools#5]

**Comment by WuSWu** [comment]
![微信截图_20240214203714](https://github.com/XDawned/ModpackLocalizationTools/assets/93047980/2246a168-a69f-462e-bf2a-44468d68102d)
我也是这个情况，但是软件可以正常启动，不知道对使用是否有影响

**Comment by XDawned** [comment]
已在#v1.1.0版本修复
