### ISSUE TITLE
更新后能否避免重复翻译，节约时间

### ISSUE THREAD

**Issue by YuFu726410** [XDawned/ModpackLocalizationTools#6]
我在更新整合包时发现整合包作者会更新FTB任务，但我之前已经翻译过一次，是否内容能先进行比对筛选，避免重复翻译，任务词条多起来全部翻译一次时间实在太长，比对上一次再进行翻译应该能节省大量时间。然后就是对于mod的翻译也是跟上面一样，能否设置任务队列避免一个个点。个人愚见，实在感谢作者的工具！！

**Comment by YuFu726410** [comment]
期待作者尽快更新，再次感谢作者能够提供这种工具

**Comment by YuFu726410** [comment]
期待作者尽快更新，再次感谢作者能够提供这种工具

**Comment by XDawned** [comment]
感谢反馈，
下个版本将会进一步优化迁移和知识库功能，实现你所说的效果

**Comment by XDawned** [comment]
已在#v1.1.0版本尝试性加入缓存机制
