### ISSUE TITLE
在其中一个翻译时会卡住，导致无法继续进行翻译

### ISSUE THREAD

**Issue by DunklerChan** [XDawned/ModpackLocalizationTools#8]
在进行模组中的一个翻译时会卡住，之后CPU占用为0，等待半个多小时没有任何动作
![卡](https://github.com/XDawned/ModpackLocalizationTools/assets/160098100/85eecbf6-3fc2-439a-98fb-053975fa44ea)

**Comment by XDawned** [comment]
我需要文件的内容来定位问题
如果内容过长，您可以粘贴在[这里](https://pastebin.ubuntu.com/)并将其地址反馈给我给我

**Comment by XDawned** [comment]
已在#v1.1.0版本修复
